config/routes.rb
Rails.application.routes.draw do

  resources :agendamentos
  resources :medicos do
    resources :agendamentos
  end
  resources :locais

  get "/administrar", to: "telaadmin#index"

  get "/agendar", to: "consulta#index"
  get "/carrega_cidade" , to: "locais#carrega_cidade"
  get "/carrega_especialidades" , to: "agendamentos#carrega_especialidades"
  match "/realizar_agendamento" => "consulta#realizar_agendamento", :via => :post
  resources :especialidades
  devise_for :usuarios #do

  #Eu tava tentando estabelecer uma rota /usuarios/sign_out pro devise fazer logout
  #mas nao deu certo. Vou deixar comentado aqui o erro
  #    Then sou redirecionada para a pagina de login de usuario # features/step_definitions/cadastro_de_medico_steps.rb:102
  #    Could not find devise mapping for path "/usuarios/sign_out".
  #    This may happen for two reasons:
  #
  #    1) You forgot to wrap your route inside the scope block. For example:
  #
  #      devise_scope :user do
  #        get "/some/route" => "some_devise_controller"
  #      end
  #
  #
  #    2) You are testing a Devise controller bypassing the router.
  #       If so, you can explicitly tell Devise which mapping to use:
  #
  #       @request.env["devise.mapping"] = Devise.mappings[:user]
  #
  #     (AbstractController::ActionNotFound)
  #    ./features/step_definitions/steps_helper.rb:70:in `cria_convidado_nao_logado'
  #    ./features/step_definitions/cadastro_de_medico_steps.rb:103:in `"sou redirecionada para a pagina de login de usuario"'
  #    features/cadastro_de_medico.feature:43:in `Then sou redirecionada para a pagina de login de usuario'

  #Failing Scenarios:
  #cucumber features/cadastro_de_medico.feature:39 # Scenario: Acesso direto sem estar logado

  #devise_scope :user do
    #get "/usuarios/sign_out", to: "devise/sessions#destroy"
    #get "/usuarios/sign_out" => "devise/sessions#destroy"
  #end

  resources :usuarios do
    resources :agendamentos
  end

  #devise_scope :usuario do
  #  get '/signout', to: 'devise/sessions#destroy', as: :signout
  #end

  #    get 'sign_out', to: 'devise/sessions#destroy'
#  end
      	  #, controllers:{
 #   sessions: 'usuarios/sessions'
  #}
#

 # Rails.application.routes.draw do
  resources :medicos
  resources :locais
  #    devise_for :users, controllers: {
   #     sessions: 'users/sessions'
    #  }
#    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/agendamento.rb
class Agendamento < ApplicationRecord
  #Somente um registro de consulta por data para determinado medico
  validates_uniqueness_of :medico, :scope => [:data ]
  #Somente um registro de consulta por data para determinado usuario(paciente)
  validates_uniqueness_of :usuario, :scope => [:data] , if: -> { usuario.present? }

  belongs_to :local
  belongs_to :especialidade
  belongs_to :medico
  belongs_to :usuario, optional: true

  ransacker :data_desejada do
    Arel.sql('date(data)')
  end

end

app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  before_action :set_agendamento, only: [:show, :edit, :update, :destroy]
  before_action :find_medico, only:[:index]
  before_action :find_paciente, only:[:index]


  def carrega_especialidades
    medico_id = params[:id].to_i
    #@estado = Estado.find(estado_id)
    #@cidades = @estado.cidades.collect { |c| [c.nome, c.id] }
    #render :layout => false
    medico = Medico.find(medico_id)
    especialidades = medico.especialidades
    esp = []
    especialidades.each do |especialidade|
      esp << {:id => especialidade.id, :n => especialidade.Nome}
    end
    render :json => {:esp => esp.compact}.as_json
  end


  # GET /agendamentos
  # GET /agendamentos.json
  def index
    medico = params[:medico_id]
    usuario = params[:usuario_id]
    if medico != nil
      @agendamentos = Agendamento.where(:medico_id => medico)
    elsif usuario != nil
      @agendamentos = Agendamento.where(:usuario_id => usuario)
    else
      @agendamentos = Agendamento.all
    end
  end

  # GET /agendamentos/1
  # GET /agendamentos/1.json
  def show
  end

  # GET /agendamentos/new
  def new
    @agendamento = Agendamento.new
  end

  # GET /agendamentos/1/edit
  def edit

    @especialidade = @agendamento.especialidade.id
  end

  # POST /agendamentos
  # POST /agendamentos.json
  def create
    @agendamento = Agendamento.new(agendamento_params)

    respond_to do |format|
      if @agendamento.save
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully created.' }
        format.json { render :show, status: :created, location: @agendamento }
      else
        format.html { render :new }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendamentos/1
  # PATCH/PUT /agendamentos/1.json
  def update
    respond_to do |format|
      if @agendamento.update(agendamento_params)
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @agendamento }
      else
        format.html { render :edit }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendamentos/1
  # DELETE /agendamentos/1.json
  def destroy
    @agendamento.destroy
    respond_to do |format|
      format.html { redirect_to agendamentos_url, notice: 'Agendamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agendamento
      @agendamento = Agendamento.find(params[:id])
    end

    def find_paciente
      @usuario = Usuario.find(params[:usuario_id]) unless params[:usuario_id].nil?
    end
    def find_medico
      @medico = Medico.find(params[:medico_id]) unless params[:medico_id].nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agendamento_params
      params.require(:agendamento).permit(:data, :local_id, :especialidade_id, :medico_id, :usuario_id)
    end
end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/views/agendamentos/_form.html.erb
<%= form_with(model: agendamento, local: true) do |form| %>
  <% if agendamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agendamento.errors.count, "error") %> prohibited this agendamento from being saved:</h2>

      <ul>
      <% agendamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.datetime_field :data %>
  </div>

  <div class="field">
    <%= form.label :local_id %><br />
    <%= form.collection_select( :local_id, Local.all, :id, :nome,  {:prompt => true}) %>
  </div>

  <div class="field">
    <%= form.label :medico_id %><br />
    <%= form.collection_select( :medico_id, Medico.all, :id, :nome,  {:prompt => true}) %>
  </div>

  <div class="field">
    <%= form.label :especialidade_id %><br />
    <%= form.collection_select( :especialidade_id, Especialidade.where(:id => @especialidade), :id, :Nome,  {:prompt => true}) %>
</div>

  <div class="field">
    <%= form.label :usuario_id %><br />
    <%= form.collection_select( :usuario_id, Usuario.all, :id, :nome,  {:prompt => true}) %>
  </div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/agendamentos/edit.html.erb
<h1>Editing Agendamento</h1>

<%= render 'form', agendamento: @agendamento %>

<%= link_to 'Show', @agendamento %> |
<%= link_to 'Back', agendamentos_path %>

app/views/agendamentos/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Agendamentos</h1>
<% if  @agendamentos != nil and @agendamentos.length > 0 %>
    <% @agendamentos.each do |agendamento| %>
    <div class="w3-container w3-card-4">
    <p> Local: <%= agendamento.local.nome %> - <%= agendamento.local.cidade.nome %> - <%= agendamento.local.cidade.estado.nome %> </p>
    <p> Medico: <%= agendamento.medico.nome %></p>
    <p> Especialidade: <%= agendamento.especialidade.Nome %></p>
    <p> CRM: <%= agendamento.medico.crm %></p>
    <p> DATA: <%= agendamento.data %> </p>

    <%if not agendamento.usuario.nil?  %>
    <p> Usuário </p>
    <p><%= agendamento.usuario.nome %></p>
    <%else %>
    <p> Usuário </p>
    <p> Nenhum até o momento </p>
    <p><%= link_to 'Show', agendamento %></p>
    <p><%= link_to 'Edit', edit_agendamento_path(agendamento) %></p>
    <p><%= link_to 'Destroy', agendamento, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <%end%>
    </div>
    <% end %>
<%else %>
<p> Não existem dados de agendamentos cadastrados! </p>
<%end %>
<%if @medico == nil and @usuario == nil %>
<%= link_to 'New Agendamento', new_agendamento_path %>
<%end %>
<%if @usuario != nil %>
<%= link_to "Agendar uma Consulta", "/agendar", :method => :get %>
<%end %>

app/views/agendamentos/new.html.erb
<h1>New Agendamento</h1>

<%= render 'form', agendamento: @agendamento %>

<%= link_to 'Back', agendamentos_path %>

app/views/agendamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @agendamento.data %>
</p>

<p>
  <strong>Local:</strong>
  <%= @agendamento.local.nome %>
</p>

<p>
  <strong>Especialidade:</strong>
  <%= @agendamento.especialidade.Nome %>
</p>

<p>
  <strong>Medico:</strong>
  <%= @agendamento.medico.nome %>
</p>

<%if not @agendamento.usuario.nil?  %>
<p>
  <strong>Usuario:</strong>
  <%= @agendamento.usuario.nome %>
</p>
<%end%>

<%= link_to 'Edit', edit_agendamento_path(@agendamento) %> |
<%= link_to 'Back', agendamentos_path %>