config/routes.rb
Rails.application.routes.draw do

  resources :agendamentos
  resources :medicos do
    resources :agendamentos
  end
  resources :locais

  get "/administrar", to: "telaadmin#index"

  get "/agendar", to: "consulta#index"
  get "/carrega_cidade" , to: "locais#carrega_cidade"
  get "/carrega_especialidades" , to: "agendamentos#carrega_especialidades"
  match "/realizar_agendamento" => "consulta#realizar_agendamento", :via => :post
  resources :especialidades
  devise_for :usuarios #do

  #Eu tava tentando estabelecer uma rota /usuarios/sign_out pro devise fazer logout
  #mas nao deu certo. Vou deixar comentado aqui o erro
  #    Then sou redirecionada para a pagina de login de usuario # features/step_definitions/cadastro_de_medico_steps.rb:102
  #    Could not find devise mapping for path "/usuarios/sign_out".
  #    This may happen for two reasons:
  #
  #    1) You forgot to wrap your route inside the scope block. For example:
  #
  #      devise_scope :user do
  #        get "/some/route" => "some_devise_controller"
  #      end
  #
  #
  #    2) You are testing a Devise controller bypassing the router.
  #       If so, you can explicitly tell Devise which mapping to use:
  #
  #       @request.env["devise.mapping"] = Devise.mappings[:user]
  #
  #     (AbstractController::ActionNotFound)
  #    ./features/step_definitions/steps_helper.rb:70:in `cria_convidado_nao_logado'
  #    ./features/step_definitions/cadastro_de_medico_steps.rb:103:in `"sou redirecionada para a pagina de login de usuario"'
  #    features/cadastro_de_medico.feature:43:in `Then sou redirecionada para a pagina de login de usuario'

  #Failing Scenarios:
  #cucumber features/cadastro_de_medico.feature:39 # Scenario: Acesso direto sem estar logado

  #devise_scope :user do
    #get "/usuarios/sign_out", to: "devise/sessions#destroy"
    #get "/usuarios/sign_out" => "devise/sessions#destroy"
  #end

  resources :usuarios do
    resources :agendamentos
  end

  #devise_scope :usuario do
  #  get '/signout', to: 'devise/sessions#destroy', as: :signout
  #end

  #    get 'sign_out', to: 'devise/sessions#destroy'
#  end
      	  #, controllers:{
 #   sessions: 'usuarios/sessions'
  #}
#

 # Rails.application.routes.draw do
  resources :medicos
  resources :locais
  #    devise_for :users, controllers: {
   #     sessions: 'users/sessions'
    #  }
#    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
  <!DOCTYPE html>
<html>

    <div class="home" id="home">
    </div>

<title>HOME</title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/assets/w3.css">

<style>


body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
body, html {
    height: 100%;
    line-height: 1.8;
}

</style>
<body>


<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-card" id="myNavbar">
    <a href="#home" class="w3-bar-item w3-button w3-wide">LOGO</a>

	<div id="user_nav">
 		<p></p>
		 <% if usuario_signed_in? %>
		        Seja bem-vindo <%= current_usuario.nome %> !


		     <%= link_to "Agendar uma Consulta", "/agendar", :method => :get %>
		     <%= link_to "Cancelar uma Consulta" %>
         <%= link_to "Minhas Consultas", usuario_agendamentos_path(current_usuario), :method => :get %>
		     <%= link_to "Minha Conta", edit_usuario_registration_path, :method => :get %>
         <% if  (current_usuario.nome  == 'admin' )  %>
          				<%= link_to "  ADMINISTRADOR", "/administrar",:method => :get %>

         <% end %>
		     <%= link_to "Sair", destroy_usuario_session_path , :method => :delete%>

		<% else %>
		    Seja bem-vindo! <%= link_to 'Criar uma nova conta', new_usuario_registration_path %> ou <%= link_to 'Entrar', 				new_usuario_session_path %>

		<% end %>

	</div>


    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <a href="#about" class="w3-bar-item w3-button">SOBRE O SUS</a>

	<!--
	<a href="#team" class="w3-bar-item w3-button"><i class="fa fa-user"></i>CRIAR CONTA</a>
      	<a href="#work" class="w3-bar-item w3-button"><i class="fa fa-th"></i>ENTRAR</a>
      -->

      <a href="#contact" class="w3-bar-item w3-button"><i class="fa fa-usd"></i>CONTATO</a>
    </div>
    <!-- Hide right-floated links on small screens and replace them with a menu icon -->

    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
</div>

<!-- Sidebar on small screens when clicking the menu icon -->
<nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">SOBRE O SUS</a>

<!--
  <a href="#team" onclick="w3_close()" class="w3-bar-item w3-button">CRIAR CONTA</a>
  <a href="#work" onclick="w3_close()" class="w3-bar-item w3-button">ENTRAR</a>
-->

  <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button">CONTATO</a>

</nav>


<!-- About Section -->
<div class="w3-container" style="padding:128px 16px" id="about">
  <h3 class="w3-center">SOBRE O SISTEMA ÚNICO DE SAÚDE - SUS</h3>
  <p class="w3-center w3-large">Principais características</p>
  <div class="w3-row-padding w3-center" style="margin-top:64px">
    <div class="w3-quarter">
      <i class="fa fa-desktop w3-margin-bottom w3-jumbo w3-center"></i>
      <p class="w3-large">Responsabilidade</p>
      <p>O Ministério da Saúde é o órgão do Poder Executivo Federal responsável pela organização e elaboração de planos e políticas públicas voltados para a promoção, a prevenção e a assistência à saúde dos brasileiros.
      É função do Ministério dispor de condições para a proteção e recuperação da saúde da população, reduzindo as enfermidades, controlando as doenças endêmicas e parasitárias e melhorando a vigilância à saúde, dando, assim, mais qualidade de vida ao brasileiro.</p>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-heart w3-margin-bottom w3-jumbo"></i>
      <p class="w3-large">Missão</p>
      <p>“Promover a saúde da população mediante a integração e a construção de parcerias com os órgãos federais, as unidades da Federação, os municípios, a iniciativa privada e a sociedade, contribuindo para a melhoria da qualidade de vida e para o exercício da cidadania"</p>
    </div>

    <!-- div class="w3-quarter">
      <i class="fa fa-diamond w3-margin-bottom w3-jumbo"></i>
      <p class="w3-large">Design</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-cog w3-margin-bottom w3-jumbo"></i>
      <p class="w3-large">Suporte</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
    </div -->

  </div>
</div>

<!-- Contact Section -->
<div class="w3-container w3-light-grey" style="padding:128px 16px" id="contact">
  <h3 class="w3-center">CONTATO</h3>
  <h2><strong>Ouvidoria-Geral do SUS</strong></h2>
  <p><strong>Telefone:</strong><span> Disque Saúde 136 (ligação gratuita)</span></p>
  <p><strong>Atendimento Presencial:<br /></strong><br />Ministério da Saúde - Esplanada dos Ministérios, Bloco G, Térreo; Brasília/DF - CEP: 70058-900.<br />Segunda a sexta-feira, das 8h às 18h.</p>
 <!-- Footer -->
<footer class="w3-center w3-black w3-padding-64">
  <a href="#home" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>IR PARA O INÍCIO</a>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>


<script>


// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}

// Toggle between showing and hiding the sidebar when clicking the menu icon
var mySidebar = document.getElementById("mySidebar");

function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
    } else {
        mySidebar.style.display = 'block';
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
}
</script>
</body>
</html>