config/routes.rb
Rails.application.routes.draw do

  resources :agendamentos
  resources :medicos do
    resources :agendamentos
  end
  resources :locais

  get "/administrar", to: "telaadmin#index"

  get "/agendar", to: "consulta#index"
  get "/carrega_cidade" , to: "locais#carrega_cidade"
  get "/carrega_especialidades" , to: "agendamentos#carrega_especialidades"
  match "/realizar_agendamento" => "consulta#realizar_agendamento", :via => :post
  resources :especialidades
  devise_for :usuarios #do

  #Eu tava tentando estabelecer uma rota /usuarios/sign_out pro devise fazer logout
  #mas nao deu certo. Vou deixar comentado aqui o erro
  #    Then sou redirecionada para a pagina de login de usuario # features/step_definitions/cadastro_de_medico_steps.rb:102
  #    Could not find devise mapping for path "/usuarios/sign_out".
  #    This may happen for two reasons:
  #
  #    1) You forgot to wrap your route inside the scope block. For example:
  #
  #      devise_scope :user do
  #        get "/some/route" => "some_devise_controller"
  #      end
  #
  #
  #    2) You are testing a Devise controller bypassing the router.
  #       If so, you can explicitly tell Devise which mapping to use:
  #
  #       @request.env["devise.mapping"] = Devise.mappings[:user]
  #
  #     (AbstractController::ActionNotFound)
  #    ./features/step_definitions/steps_helper.rb:70:in `cria_convidado_nao_logado'
  #    ./features/step_definitions/cadastro_de_medico_steps.rb:103:in `"sou redirecionada para a pagina de login de usuario"'
  #    features/cadastro_de_medico.feature:43:in `Then sou redirecionada para a pagina de login de usuario'

  #Failing Scenarios:
  #cucumber features/cadastro_de_medico.feature:39 # Scenario: Acesso direto sem estar logado

  #devise_scope :user do
    #get "/usuarios/sign_out", to: "devise/sessions#destroy"
    #get "/usuarios/sign_out" => "devise/sessions#destroy"
  #end

  resources :usuarios do
    resources :agendamentos
  end

  #devise_scope :usuario do
  #  get '/signout', to: 'devise/sessions#destroy', as: :signout
  #end

  #    get 'sign_out', to: 'devise/sessions#destroy'
#  end
      	  #, controllers:{
 #   sessions: 'usuarios/sessions'
  #}
#

 # Rails.application.routes.draw do
  resources :medicos
  resources :locais
  #    devise_for :users, controllers: {
   #     sessions: 'users/sessions'
    #  }
#    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/medico.rb
class Medico < ApplicationRecord
  has_and_belongs_to_many :especialidades 
  accepts_nested_attributes_for :especialidades
  validates_presence_of :nome, :message => "- Campo obrigatorio"

  #fix-it:Validar crm corretamente daria mais trabalho do que isso que eu fiz. Por enquanto exige apenas numeros
  #http://www.guj.com.br/t/validacao-de-crm-conelho-regional-de-medicina/110130
  validates_presence_of :crm, :message => "- Campo obrigatorio"
  #Fix-it: Arrumar o testes pra usar essa validacao
  #validates :crm, :uniqueness => true   #Nao permite crm que ja tenha sido utilizado anteriormente

  validates_presence_of :local, :message => "- Campo obrigatorio"
  validates_presence_of :email, :message => "- Campo obrigatorio"
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }  #exige um email valido
  validates :email, :uniqueness => true   #idem crm

  validates_presence_of :sexo, :message => "- Campo obrigatorio"
  validates_presence_of :situacao, :message => "- Campo obrigatorio"
  #validates_presence_of :especialidade_id, :message => "can't be empty"
  has_many :agendamentos
  has_many :locais, :through => :agendamentos
  has_many :usuarios, :through => :agendamentos
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController  
  before_action :authenticate_usuario!
  before_action :set_medico, only: [:show, :edit, :update, :destroy]
  # GET /medicos
  # GET /medicos.json

  def verifica_se_usuario_logado_e_admin
    @usuario_logado = current_usuario
    if @usuario_logado.nome != "admin"
      sign_out :usuario
      redirect_to "/usuarios/sign_in"
    end
  end
  
  def index
    puts "###[medicos_controller] def index..."
    verifica_se_usuario_logado_e_admin
    #redirect_to :root
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
    verifica_se_usuario_logado_e_admin
  end

  # GET /medicos/new
  def new
    puts "###[medicos_controller.rb] def new..."
    verifica_se_usuario_logado_e_admin
    @medico = Medico.new
    @especialidade = Especialidade.all
  end

  # GET /medicos/1/edit
  def edit    
    puts "###[medicos_controller] def edit..."
    verifica_se_usuario_logado_e_admin
    @especialidade = Especialidade.all
  end

  # POST /medicos
  # POST /medicos.json
  def create
    puts "###[medicos_controller] def create..."
    verifica_se_usuario_logado_e_admin
    @medico = Medico.new(medico_params)
    @params = params #consultando parametros
    #PESSOAL, quando o botao do create new e pressionado precisamos dos parametros
    #pra poder ver se vieram especialidades no parametro.
    #la no form tem um esquema que prefixa com esp_ todas as especialidades checadas
    #entao a gente pega os parametros que comacam com esp_ e o valor do parametro e
    #justamente o id da especialidade.
    #Entao a gente usa esse id da especialidade pra dar um find e obter o registro dessa especialidade
    @params.each do |p|
      puts p
      if p[0].start_with?("esp_");
        esp = Especialidade.find(p[1]);
        @medico.especialidades << esp
      end      
    end

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    puts "update..."
    verifica_se_usuario_logado_e_admin
    respond_to do |format|
      if @medico.update(medico_params)
        colhe_especialidades_from_params(params)
        atribui_especialidades_nao_repetidas_ao_medico()        

        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end


  def colhe_especialidades_from_params(parametros)
    @especialidades_from_params = Array.new
    i = -1
    @params = parametros
    @params.each do |p|
      if p[0].start_with?("esp");
        i = i + 1;
        oEsp = Especialidade.find(p[1])
        @especialidades_from_params[i] = oEsp
      end                          
    end
  end

  def atribui_especialidades_nao_repetidas_ao_medico()
    #https://apidock.com/rails/ActiveRecord/Associations/CollectionProxy
    if !@medico.especialidades.any?
      for esp_from_param in @especialidades_from_params do
        #caso o medico nao tenha nehuma especialidade nao ha comparacoes a ser feitas
        #apenas atribuimos a especialidade a ele e pronto
        #if !esp_from_param.nil?
        @medico.especialidades << esp_from_param
        # end
      end
    else
      #mas se o medico ja tem alguma especialidade, entao nao he so atribuir
      #precisa realizar comparacoes pra nao atribuir especialidades que ele ja tem
      for esp_from_param in @especialidades_from_params do
        puts "###[medicos_controller.rb] for esp_from_param in @especialidades_from_params do.."
        for esp_do_medico in @medico.especialidades  do
          #if !esp_from_param.nil? && ( esp_from_param.id == esp_do_medico.id)
          medico_tem_essa = false
          if esp_from_param.id == esp_do_medico.id
            medico_tem_essa = true
            break
          end
        end
        if !medico_tem_essa
          @medico.especialidades << esp_from_param
        end
      end #for
    end
  end #def
  
  def checa_se_ha_params_que_sao_especialidades_e_atribui_ao_medico(parametros)
    @params = parametros
    @params.each do |p|
      if p[0].start_with?("esp");
        esp = Especialidade.find(p[1]);
        @medico.especialidades << esp
      end                          
    end
  end
  
  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    verifica_se_usuario_logado_e_admin
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'Medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      #fix-me
      #fiz isso para estudo...
      #params.require(:medico).permit(:nome, :crm, :local, :telefone, :celular, :email, :sexo, :situacao)
       params.require(:medico).permit!
    end
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/medicos/_form.html.erb
<%= form_with(model: medico, local: true) do |form| %>

    
    <% if medico.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>            
            <ul>
                <% medico.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :nome%>
        <%= form.text_field :nome %>
    </div>

    <div class="field">
        <%= form.label :crm %>
        <%= form.text_field :crm %>
    </div>

    <div class="field">
        <%= form.label :local %>
        <%= form.text_field :local %>
    </div>

    <div class="field">
        <%= form.label :telefone %>
        <%= form.text_field :telefone %>
    </div>

    <div class="field">
        <%= form.label :celular %>
        <%= form.text_field :celular %>
    </div>

    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>

    <div class="field">
        <%= form.label :sexo %>
        <%= form.text_field :sexo %>
    </div>

    <div class="field">
        <%= form.label :situacao %>
        <%= form.text_field :situacao %>
    </div>

    
    <span><strong>Especialidades deste M&eacute;dico</strong></span></br>
    <% if @medico.especialidades.length > 0 %>
        <% @medico.especialidades.each do | e | %>
            <li><%= e.Nome %></li>
        <% end %>
        <hr></hr>
    <% else %>
        <span>Este m&eacute;dico ainda n&atilde;o tem especialidade:</span>
        <hr></hr>
    <% end %>
    
    <hr></hr>

    <!-- 
         <span>Especialidades Existentes:</span><br>
         <%= form.fields_for :especialidades do |especialidade_fields| %>
         <% if especialidade_fields.object != nil? %>
         Esp: <%= especialidade_fields.text_field :Nome %>
         <% end %>
         <% end %>
    -->

    <span><strong>Especialidades Existentes:</strong></span><br>

    <% if (@especialidade == nil) %>
        <%= "Nao exitem especialidades cadastradas" %>
    <% else %>    
        <% for @item in @especialidade %>
            <%= check_box_tag  "esp_" + @item.Nome, @item.id, checked = false %><%= @item.Nome %><br></br>
        <% end %>
    <% end %>
     
    
       
    
    

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medicos/edit.html.erb
<header class="w3-container w3-teal">
  <h1>Agende R&aacute;pido - Editar M&eacute;dico</h1>
</header>
<div class="w3-container w3-half w3-margin-top">
<div class="w3-container w3-card-4">


<!-- h1>Editar Medico</h1 -->

<%= render 'form', medico: @medico %>
<%= link_to 'Mostrar', @medico %> |
<%= link_to 'Voltar', medicos_path %>

app/views/medicos/index.html.erb
<header class="w3-container w3-teal">
  <h1>Agende R&aacute;pido - Listar M&eacute;dicos</h1>
</header>

<div class="w3-container w3-quarter{float:left;width:100%} w3-margin-top">
<div class="w3-container w3-card-4">


<p id="notice"><%= notice %></p>


<table class="w3-table-all">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Crm</th>
      <th>Local</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Sexo</th>
      <th>Situacao</th>
      <th>Especialidades</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= medico.nome %></td>
        <td><%= medico.crm %></td>
        <td><%= medico.local %></td>
        <td><%= medico.telefone %></td>
        <td><%= medico.celular %></td>
        <td><%= medico.email %></td>
        <td><%= medico.sexo %></td>
        <td><%= medico.situacao %></td>
        <td>
        <% medico.especialidades.each do | e | %>
           <%= e.Nome %>
        <% end %>
        </td>

        <td><%= link_to 'Mostrar', medico %></td>
        <td><%= link_to 'Editar', edit_medico_path(medico) %></td>
        <td><%= link_to 'Excluir', medico, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'Novo Medico', new_medico_path %>

app/views/medicos/new.html.erb
<header class="w3-container w3-teal">
    <h1>Agende R&aacute;pido - Cadastrar Novo Medico</h1>
</header>

<div class="w3-container w3-half w3-margin-top">
<div class="w3-container w3-card-4">

<%= render 'form', medico: @medico %>
<%= link_to 'Voltar', medicos_path %>

app/views/medicos/show.html.erb
<header class="w3-container w3-teal">
  <h1>Agende R&aacute;pido - Visualizar M&eacute;dico</h1>
</header>
<div class="w3-container w3-half w3-margin-top">
<div class="w3-container w3-card-4">


<p id="notice"><%= notice %></p>
<p>
  <strong>Nome:</strong>
  <%= @medico.nome %>
</p>

<p>
  <strong>Crm:</strong>
  <%= @medico.crm %>
</p>

<p>
  <strong>Local:</strong>
  <%= @medico.local %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @medico.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @medico.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @medico.email %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @medico.sexo %>
</p>

<p>
    <strong>Situacao:</strong>
    <%= @medico.situacao %>
</p>

<p>
    <strong>Especialidades:</strong>
    <% if @medico.especialidades != nil? %>
        <% @medico.especialidades.each do |e|  %>
            <%= e.Nome %>        
        <% end %>
    <% end  %>
</p>

<%= link_to 'Editar', edit_medico_path(@medico) %> |
<%= link_to 'Voltar', medicos_path %>